#[derive(Copy, Clone)]
pub struct Theme<'a> {
    pub name : &'a str,
    pub id : u8,
    pub bg : u16,
    pub text : u16,
    pub subtext : u16,
    pub overlay : u16,
    pub accent : u16,
    pub secondary_accent : u16,
    pub tertiary_accent : u16,
}

pub fn theme<'a>(theme: Option<u8>) -> Theme<'a> {
    match theme {
        Some(0) => Theme  {
            name : "Numworks Light\0",
            id : 0,
            bg : 0xffff,
            text : 0x0000,
            subtext: 0x4a69,
            overlay : 0xe71c,
            accent : 0xfde9,
            secondary_accent : 0xe548,
            tertiary_accent : 0xcca7,
        },
        Some(1) => Theme {
            name : "Numworks Dark\0",
            id : 1,
            bg : 0x18c3,
            text : 0xffff,
            subtext: 0xe71c,
            overlay : 0x4a69,
            accent : 0xfde9,
            secondary_accent : 0xe548,
            tertiary_accent : 0xcca7,
        },
        Some(2) => Theme {
            name : "Omega Light\0",
            id : 2,
            bg : 0xffff,
            text : 0x0000,
            subtext: 0x4a69,
            overlay : 0xe71c,
            accent : 0xe1c7,
            secondary_accent : 0xb9c7,
            tertiary_accent : 0x9145,
        },
        Some(3) => Theme {
            name : "Omega Dark\0",
            id : 3,
            bg : 0x18c3,
            text : 0xffff,
            subtext: 0xe71c,
            overlay : 0x4a69,
            accent : 0xe1c7,
            secondary_accent : 0xb9c7,
            tertiary_accent : 0x9145,
        },
        Some(4) => Theme {
            name : "Candy\0",
            id : 4,
            bg : 0x1967,
            text : 0xc77e,
            subtext : 0x95b7,
            overlay : 0x3a0c,
            accent : 0x5ef9,
            secondary_accent : 0x73fa,
            tertiary_accent : 0xea93,
        },
        _ => Theme {
            name : "Numworks Light\0",
            id : 0,
            bg : 0xffff,
            text : 0x0000,
            subtext: 0x4a69,
            overlay : 0xe71c,
            accent : 0xfde9,
            secondary_accent : 0xe548,
            tertiary_accent : 0xcca7,
        },
    }
}